import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export async function POST(request: Request) {
  try {
    // Check if API key is configured
    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        { error: 'Email service not configured. Please add RESEND_API_KEY to environment variables.' },
        { status: 500 }
      );
    }

    const resend = new Resend(process.env.RESEND_API_KEY);

    const { recipientEmail, propertyTitle, slug, phpCode, cssCode, jsonData } = await request.json();

    if (!recipientEmail || !propertyTitle) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Send email with all 3 files
    const { data, error } = await resend.emails.send({
      from: 'Brenda Listings <onboarding@resend.dev>', // You'll customize this later
      to: [recipientEmail],
      subject: `New Property Listing Generated: ${propertyTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #2563eb;">🏡 New Property Listing Generated</h1>
          
          <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="margin-top: 0;">${propertyTitle}</h2>
            <p><strong>Slug:</strong> ${slug}</p>
            <p><strong>Generated by:</strong> Brenda Devlin's Listings Page</p>
          </div>

          <h3>📦 WordPress Installation Files</h3>
          <p>Below are the 3 files needed to create this listing in WordPress:</p>

          <div style="background: #ede9fe; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h4 style="color: #7c3aed; margin-top: 0;">Step 1️⃣: PHP Code</h4>
            <p style="font-size: 14px;">Add to: <code>Snippets → Add New</code></p>
            <p style="font-size: 12px; color: #6b7280;">Remove &lt;?php and ?&gt; tags when pasting into Code Snippets</p>
          </div>

          <div style="background: #fce7f3; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h4 style="color: #db2777; margin-top: 0;">Step 2️⃣: CSS Styles</h4>
            <p style="font-size: 14px;">Add to: <code>Appearance → Customize → Additional CSS</code></p>
          </div>

          <div style="background: #dcfce7; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h4 style="color: #16a34a; margin-top: 0;">Step 3️⃣: JSON Data</h4>
            <p style="font-size: 14px;">Add to: <code>Custom Field: property_listing_json</code></p>
            <p style="font-size: 14px;">Then add shortcode: <code>[property_listing]</code></p>
          </div>

          <hr style="border: 1px solid #e5e7eb; margin: 30px 0;">

          <h3>📄 Files Attached</h3>
          <p>The PHP, CSS, and JSON files are included below. Copy and paste each one into WordPress following the steps above.</p>

          <div style="background: #1f2937; color: #10b981; padding: 20px; border-radius: 8px; margin: 20px 0; font-family: monospace; font-size: 12px;">
            <h4 style="color: #10b981; margin-top: 0;">📝 PHP Code (property-listing-shortcode.php):</h4>
            <pre style="white-space: pre-wrap; word-wrap: break-word;">${phpCode.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
          </div>

          <div style="background: #1f2937; color: #60a5fa; padding: 20px; border-radius: 8px; margin: 20px 0; font-family: monospace; font-size: 12px;">
            <h4 style="color: #60a5fa; margin-top: 0;">🎨 CSS Code (property-listing-styles.css):</h4>
            <pre style="white-space: pre-wrap; word-wrap: break-word;">${cssCode}</pre>
          </div>

          <div style="background: #1f2937; color: #34d399; padding: 20px; border-radius: 8px; margin: 20px 0; font-family: monospace; font-size: 12px;">
            <h4 style="color: #34d399; margin-top: 0;">🔌 JSON Data (listing-${slug}.json):</h4>
            <pre style="white-space: pre-wrap; word-wrap: break-word;">${jsonData}</pre>
          </div>

          <hr style="border: 1px solid #e5e7eb; margin: 30px 0;">

          <p style="color: #6b7280; font-size: 14px;">
            This email was generated automatically from Brenda Devlin's Listings Page.<br>
            If you have any questions, please contact your administrator.
          </p>
        </div>
      `,
    });

    if (error) {
      console.error('Resend error:', error);
      return NextResponse.json(
        { error: 'Failed to send email', details: error },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      messageId: data?.id,
      message: 'Email sent successfully!'
    });

  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email', details: error },
      { status: 500 }
    );
  }
}

